### ISSUE TITLE
CDN Diagnostics Logs

### ISSUE THREAD

**Issue by dimilider** [tyconsulting/azurepolicy#1]
Applying the CDN policy ist not working because of the following error:
Error code
RemediatedResourceNotFound

Reason
The resource being remediated '/subscriptions/<subscriptionID>/resourcegroups/<RGname>/providers/microsoft.cdn/profiles/<CDNProfileName>/endpoints/<EndpointName>' could not be retrieved.

**Comment by tyconsulting** [comment]
> Applying the CDN policy ist not working because of the following error:
> Error code
> RemediatedResourceNotFound
> 
> Reason
> The resource being remediated '/subscriptions//resourcegroups//providers/microsoft.cdn/profiles//endpoints/' could not be retrieved.

I tested the remediation against a brown field resource. the remediation worked. however, although I can query the diagnosticSettings using ARM REST API after remediation, but I can't see it in the portal. Wondering if this is a bug in the portal. closing this issue now
