### ISSUE TITLE
diagnostic settings API version not supported

### ISSUE THREAD

**Issue by ehrnst** [tyconsulting/azurepolicy#12]
I tried using 2018-06-01 but got this error. 
![image](https://user-images.githubusercontent.com/21357174/84035654-5d16f780-a99c-11ea-9f4b-331cf06af78c.png)

Looking at in [the API docs](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/allversions) diagnosticSettings is only mentioned in 2017-05-01-preview.
Am I the only one having this issue?

**Comment by jonathan-vella** [comment]
I have the same issue. Have you managed to find a solution?

**Comment by ehrnst** [comment]
i am running with 2017-05-01-preview again

**Comment by AzureStackNinja** [comment]
I have the same problem.

**Comment by madforchili** [comment]
did 2017-05-01-preview worked?  2016-09-01 was getting different error 

"Path: '/subscriptions/xxxxxxxxxxxxxxxx/resourcegroups/af-rg-uat/providers/Microsoft.Network/networkInterfaces/af-ep-kv-uat.nic.xxxxxxxxxxxxxxxx/providers/Microsoft.Insights/diagnosticSettings/setByPolicy' is not supported"

**Comment by tyconsulting** [comment]
updated API version
