### ISSUE TITLE
Diagnostic Setting doesn't work for Virtual Machines

### ISSUE THREAD

**Issue by coulsonr** [tyconsulting/azurepolicy#18]
I don't believe this works with Virtual Machines anymore. The Virtual Machine blade for Diagnostics doesn't even take a log analytics workspace as input. Is there a different blade menu for Virtual Machines this was intended for that I'm not seeing? See screen shot for reference. 

![VMDiagnostics](https://user-images.githubusercontent.com/4430117/111696172-fc0d3180-8801-11eb-8a3c-8c48d2af2f9e.png)

**Comment by tyconsulting** [comment]
it's not available via the portal, but indeed supported (you can verify it using this REST API: https://docs.microsoft.com/en-us/rest/api/monitor/diagnostic-settings-category/get

**Comment by Torxsmind** [comment]
I have the same question.  Does not seem like anything is going to the Log analytics with the policy here.
