### ISSUE TITLE
Metrics category in diagnostic settings for API Management services need to be updated

### ISSUE THREAD

**Issue by ctvue** [tyconsulting/azurepolicy#19]
https://github.com/tyconsulting/azurepolicy/blob/master/policy-definitions/resource-diagnostics-settings/log-analytics/azurepolicy.apiMgmt-la.json

During testing, "create or update resource diagnostic setting" operation failed.  The supported Metric categories are "AllMetrics" and should be updated accordingly.

- Error code = _BadRequest_ 
- Message = _Metric category 'Gateway Requests' is not supported, supported categories are: 'AllMetrics'_

**Comment by tyconsulting** [comment]
updated
