### ISSUE TITLE
Wrong parameters for deployment section in azurepolicy.vnet-eh.json

### ISSUE THREAD

**Issue by techlake** [tyconsulting/azurepolicy#20]
Hi, the above policy has a mistake starting with the parameters on line 88. you copied the parameters from the Log analytics version (it appears). the correct block is below. I hope this helps.
                "parameters": {
                  "diagnosticsSettingNameToUse": {
                    "type": "string"
                  },
                  "resourceName": {
                    "type": "string"
                  },
                  **"eventHubName": {
                    "type": "string"
                  },
                  "eventHubAuthorizationRuleId": {
                    "type": "string"
                  },**
                  "location": {
                    "type": "string"
                  }
                },

**Comment by tyconsulting** [comment]
fixed
